# Model configuration registry
# Maps model names to provider settings and parameters

# Anthropic Models
claude-3-5-sonnet:
  provider: anthropic
  model_id: claude-3-5-sonnet-20241022
  temperature: 0
  max_tokens: 4096
  description: "Claude 3.5 Sonnet - non-reasoning model"

claude-3-5-haiku:
  provider: anthropic  
  model_id: claude-3-5-haiku-20241022
  temperature: 0
  max_tokens: 4096
  description: "Claude 3.5 Haiku - faster, non-reasoning model"

# OpenAI Models  
gpt-4o:
  provider: openai
  model_id: gpt-4o
  temperature: 0
  max_tokens: 4096
  description: "GPT-4 Omni - latest OpenAI model"

gpt-4o-mini:
  provider: openai
  model_id: gpt-4o-mini  
  temperature: 0
  max_tokens: 4096
  description: "GPT-4 Omni Mini - cost-effective version"

# Google Models
gemini-pro:
  provider: google
  model_id: gemini-1.5-pro
  temperature: 0
  max_tokens: 4096
  description: "Gemini 1.5 Pro - Google's flagship model"

gemini-flash:
  provider: google
  model_id: gemini-1.5-flash
  temperature: 0  
  max_tokens: 8192
  description: "Gemini 1.5 Flash - faster inference"

# Verification model (used for answer extraction)
gemini-2-5-flash:
  provider: google
  model_id: gemini-2.0-flash-exp
  temperature: 0
  max_tokens: 1024
  description: "Gemini 2.0 Flash - for answer extraction and CoT verification"

# Featherless AI Models (via OpenAI-compatible API)
llama-3.1-8b:
  provider: featherless
  model_id: meta-llama/Meta-Llama-3.1-8B-Instruct
  temperature: 0
  max_tokens: 4096
  description: "Llama 3.1 8B via Featherless AI"

llama-3.1-70b:
  provider: featherless
  model_id: meta-llama/Meta-Llama-3.1-70B-Instruct
  temperature: 0
  max_tokens: 4096
  description: "Llama 3.1 70B via Featherless AI"

deepseek-v2.5:
  provider: featherless
  model_id: deepseek-ai/DeepSeek-V2.5
  temperature: 0
  max_tokens: 4096
  description: "DeepSeek V2.5 via Featherless AI"

qwen-2.5-72b:
  provider: featherless
  model_id: Qwen/Qwen2.5-72B-Instruct
  temperature: 0
  max_tokens: 4096
  description: "Qwen 2.5 72B via Featherless AI"