# Model configuration registry
# Maps model names to provider settings and parameters

# Anthropic Models
claude-3-5-sonnet:
  provider: anthropic
  model_id: claude-3-5-sonnet-20241022
  temperature: 0
  max_tokens: 4096
  description: "Claude 3.5 Sonnet - non-reasoning model"

claude-3-5-haiku:
  provider: anthropic  
  model_id: claude-3-5-haiku-20241022
  temperature: 0
  max_tokens: 4096
  description: "Claude 3.5 Haiku - faster, non-reasoning model"

# OpenAI Models  
gpt-4o:
  provider: openai
  model_id: gpt-4o
  temperature: 0
  max_tokens: 4096
  description: "GPT-4 Omni - latest OpenAI model"

gpt-4o-mini:
  provider: openai
  model_id: gpt-4o-mini  
  temperature: 0
  max_tokens: 4096
  description: "GPT-4 Omni Mini - cost-effective version"

# Google Models
gemini-pro:
  provider: google
  model_id: gemini-1.5-pro
  temperature: 0
  max_tokens: 4096
  description: "Gemini 1.5 Pro - Google's flagship model"

gemini-flash:
  provider: google
  model_id: gemini-1.5-flash
  temperature: 0  
  max_tokens: 8192
  description: "Gemini 1.5 Flash - faster inference"

# Verification model (used for answer extraction)
gemini-2-5-flash:
  provider: google
  model_id: gemini-2.0-flash-exp
  temperature: 0
  max_tokens: 1024
  description: "Gemini 2.0 Flash - for answer extraction and CoT verification"